### PR TITLE
Introduce defcustoms, fix docstring

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by swflint** [comment]
If you'd split the defgroup/defcustom and the docstring change, I'll accept them both.

**Comment by purcell** [comment]
I submitted these as a favour to help you get the package into MELPA. Sorry, but I'm not going to go back and split them.

**Comment by swflint** [comment]
I'll accept it, but for future reference I tend to like different things committed separately.

**Comment by swflint** [comment]
Merged.

**Pull request merged**
